### ISSUE TITLE
Cambio en el boton de la pagina de reportes (http://localhost:4200/report?idEscuela=1)

### ISSUE THREAD

**Issue by Osman-Suastegui** [JuanNajera02/FrontEnd-Primaria#1]
![image](https://github.com/JuanNajera02/FrontEnd-Primaria/assets/69287071/86a85fcc-4dfc-43b2-96be-cc89043d9a90)

Quiero que el boton no diga "Limpiar filtros" ahora va a decir "buscar"

**Comment by Emelport** [comment]
Ok, lo checo
